apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghtfgg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghtfgg
  template:
    metadata:
      labels:
        app: ghtfgg
    spec:
      containers:
      - image: okteto.dev/ghtfgg:latest
        name: ghtfgg
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "56234054-335f-4dce-99c9-10d9ee51a3f9"
        - name: Vless_Path
          value: "/vlessaa"
        - name: Vmess_UUID
          value: "56234054-335f-4dce-99c9-10d9ee51a3f9"
        - name: Vmess_Path
          value: "/vmessbb"
        - name: Share_Path
          value: "$Share_Path"
